services:
  - type: web
    name: thrift-in-campus
    runtime: node
    plan: free
    autoDeployTrigger: commit
    buildCommand: npm install && npx prisma db push && npm run db:seed && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        value: "file:./dev.db"
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: "https://thrift-in-campus.onrender.com"
